name: My-test
on:
  workflow_dispatch:
    inputs:
      sample:
        type: choice
        options:
          - 'A'
          - 'B'
        description: Sample Data to test
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Sample Test
        if: github.event.inputs.sample == 'A'
        run: echo "Hello"
      - name: Sample Test from script
        if: github.event.inputs.sample == 'B'
        run: |
         chmod +x ./scripts/print.sh
         ./scripts/print.sh
         shell: bash
